server:
  port: 8082


spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver




# MP配置
mybatis-plus:
  # 配置mapper的扫描，找到所有的 mapper.xml 映射文件
  type-aliases-package: com.test.learn.**.entity,com.test.learn.**.dto
  # 搜索指定包别名
  mapper-locations: classpath*:mybatis/**/*Mapper.xml



#PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  autoRuntimeDialect: true